// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qykvpadkdjopporzawxi.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InF5a3ZwYWRrZGpvcHBvcnphd3hpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzA5NTQ1MjAsImV4cCI6MjA4NjUzMDUyMH0.5imoBGl1BwUf9UZXwk32iuGWflb4E40wIvqqdckWH9U";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});